admin/dist/index.html
admin/src/scripts/router.js
admin/src/styles/app.css

* Removed small horizontal scroll, which came from ```main.css```
* avoid blinking Yes/No confirmation dialog
* Download button is always shown.

Fixes related to #26. Closes #26.

---

admin/dist/index.html
admin/src/scripts/components/ui/bigbang.js
admin/src/scripts/components/ui/descriptoredit.js
admin/src/scripts/components/ui/download.js
admin/src/scripts/components/ui/registry.js
admin/src/scripts/components/ui/upload.js
admin/src/scripts/router.js
package.json

* Updated ```package.json```
* refined every piece of code which utilized ```datapackage-validate``` to work with Promises
* did some refactoring.

Use Promised fork of datapackage-validate. Closes #27.

---

datapackagist/src/scripts/components/ui/descriptoredit.js

* In real time place name field value into title field
* replace ```-```, ```_```, ```.``` and snakeCase with space
* ignore name field value if user has edited title field
* fill up title field with name field value once user empties the title.

Populate title field with name field value. Closes #60.

---

datapackagist/dist/index.html
datapackagist/src/scripts/components/ui/descriptoredit.js
datapackagist/src/styles/app.css
gulpfile.js

More details here https://github.com/okfn/datapackagist/issues/46#issuecomment-116669341

Numerous UI/UX updates of edit form

---

datapackagist/src/scripts/components/ui/registry.js
datapackagist/src/scripts/router.js
gulpfile.js

* Changes URL path structure used for action of mapping remote data into datapackage — ```/base/from/?url=...```
* provide URL path param to set registry profiles select box into certain value
* refined routes handlers.

Define registry list profile from query string param. Closes #78.

---

datapackagist/src/scripts/components/ui/descriptoredit.js

Remove empty resource row on upload file (#77)

---

datapackagist/src/scripts/components/ui/registry.js
package.json

Was replaced promise-polyfill to bluebird.

Replace promise-polyfill to bluebird (#71)

---

datapackagist/src/scripts/components/ui/descriptoredit.js
datapackagist/src/styles/app.css

Mark required field by span.required-field
Closes #81

Mark required label (#81)

---

datapackagist/src/scripts/app.js
datapackagist/src/scripts/router.js
gulpfile.js

* Removed browsersync middleware
* edited Backbone router options
* updated routes routines.

Prefix app URLs pathes with #

---

datapackagist/src/scripts/components/ui/descriptoredit.js
datapackagist/src/scripts/components/ui/validationresult.js
package.json

If resource is defined as URL
* download CSV (only CSV at the moment)
* get its schema using ```json-table-schema```
* validate downloaded resource over schema.

Validate resources passed as URL

---

datapackagist/src/scripts/components/ui/descriptoredit.js

Fix extra resource item row when switching from base to tabular profile

---

datapackagist/dist/index.html
datapackagist/src/scripts/components/ui/bigbang.js
datapackagist/src/scripts/components/ui/descriptoredit.js
datapackagist/src/scripts/components/ui/validationresult.js

* Added validation ok message
* did some refactoring — decoupled validation routine.

Resource validation messages. Closes #99.

---

datapackagist/src/scripts/components/ui/download.js

Inject custom error message into form for fields which are not valid by ```.anyOf``` property of the schema.

Show verbose validation error

---

datapackagist/src/scripts/router.js

Fix loading remote data package in Firefox.

FireFox parse url bug. Fixes #107.

---

datapackagist/src/scripts/components/ui/jsoneditform.js
package.json

Replace omit-empty to deep-compact for fix Safari issue (#136)

---

.gitignore
datapackagist/app.js
datapackagist/src/scripts/components/ui/resource-editor.js
datapackagist/src/scripts/config.js
tests/index.js

Fixes errors shown in console while trying to activate resources validation dialog.

Fix resources validation bug. Closes #170.

---

datapackagist/src/scripts/config.js
datapackagist/src/scripts/router.js

added new proxy; using proxy in datapackage-from-remote-js

---

index.html

- connects https://github.com/okfn/devops/issues/142

Switched from default GA to Consent Manager

---

data/datapackage.json

- fixes #247 
---
Tested metadata addition - it works

Added a test datapackage

---

data/datapackage-with-missing-values.json
data/table.csv
jest.config.js
package.json
src/reducers/__tests__/editorPackage.test.js
src/reducers/editorPackage.js

Fixed the missing value error
